management:
  endpoints:
    web:
      exposure:
        include: sbom

  endpoint:
    sbom:
      additional:
        native-image:
          location: "optional:classpath:META-INF/sbom/application.cdx.json"