output:
  - "cyclonedx-json"

quiet: false
check-for-app-update: false
parallelism: 4

scope: "squashed"

select-catalogers: ["+sbom-cataloger"]

format:
  cyclonedx-json:
    pretty: false

file:
  metadata:
    selection: "all"
    digests:
      - "sha256"
      - "sha512"
  content:
    skip-files-above-size: 1024
    globs: []

package:
  search-indexed-archives: true
  search-unindexed-archives: false
  exclude-binary-overlap-by-ownership: true

java:
  maven-url: "https://repo1.maven.org/maven2"
  max-parent-recursive-depth: 5
  use-network: true

source:
  image:
    default-pull-source: "registry"

registry:
  insecure-skip-tls-verify: false
  insecure-use-http: false

log:
  structured: false
  level: "error"
